# Generated by Django 5.1.7 on 2025-04-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('sur_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
