# Generated by Django 5.1.7 on 2025-04-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_title', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
