# Generated by Django 5.1.7 on 2025-04-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='taken_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_course', to='home.course'),
        ),
    ]
